// #Misfits Add — Standalone ticket log window showing all current-round tickets.
// Opened from the Staff tab button in the Admin Menu.
using System.Linq;
using Content.Client.Administration.Systems;
using Content.Shared._Misfits.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Utility;

namespace Content.Client._Misfits.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class TicketLogWindow : DefaultWindow
{
    [Dependency] private readonly IEntitySystemManager _entitySystem = default!;

    private readonly Dictionary<int, HelpTicketInfo> _tickets = new();
    private readonly BwoinkSystem _bwoinkSys;

    public TicketLogWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _bwoinkSys = _entitySystem.GetEntitySystem<BwoinkSystem>();

        _bwoinkSys.OnTicketUpdated += OnTicketUpdated;
        _bwoinkSys.OnTicketListReceived += OnTicketListReceived;

        RefreshTickets.OnPressed += _ => _bwoinkSys.RequestTicketList();

        // Fetch current list on open
        _bwoinkSys.RequestTicketList();
    }

    private void OnTicketUpdated(HelpTicketInfo ticket)
    {
        _tickets[ticket.TicketId] = ticket;
        RebuildList();
    }

    private void OnTicketListReceived(List<HelpTicketInfo> tickets)
    {
        foreach (var t in tickets)
            _tickets[t.TicketId] = t;

        RebuildList();
    }

    private void RebuildList()
    {
        TicketListContainer.RemoveAllChildren();

        // Open first, then claimed, then resolved; newest within each group
        var sorted = _tickets.Values
            .OrderBy(t => t.Status)
            .ThenByDescending(t => t.CreatedAt);

        foreach (var ticket in sorted)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 4,
            };

            row.AddChild(new Label { Text = $"#{ticket.TicketId}", MinWidth = 60 });
            row.AddChild(new Label { Text = ticket.PlayerName, MinWidth = 140 });

            var statusLabel = new RichTextLabel { MinWidth = 120 };
            var statusMsg = new FormattedMessage();
            var (color, text) = ticket.Status switch
            {
                HelpTicketStatus.Open => ("red", Loc.GetString("ticket-system-status-open")),
                HelpTicketStatus.Claimed => ("yellow", Loc.GetString("ticket-system-status-claimed", ("admin", ticket.ClaimedByName ?? "?"))),
                HelpTicketStatus.Resolved => ("green", Loc.GetString("ticket-system-status-resolved")),
                _ => ("gray", "Unknown"),
            };
            statusMsg.AddMarkup($"[color={color}]{text}[/color]");
            statusLabel.SetMessage(statusMsg);
            row.AddChild(statusLabel);

            row.AddChild(new Label { Text = ticket.ClaimedByName ?? "—", MinWidth = 140 });
            row.AddChild(new Label { Text = ticket.CreatedAt.ToString("HH:mm:ss"), MinWidth = 120 });

            TicketListContainer.AddChild(row);
        }
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        _bwoinkSys.OnTicketUpdated -= OnTicketUpdated;
        _bwoinkSys.OnTicketListReceived -= OnTicketListReceived;
    }
}
