// #Misfits Change - Whitelist Search admin panel code-behind
using System.Threading;
using Content.Client.Administration.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared._Misfits.Administration;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Timer = Robust.Shared.Timing.Timer;

namespace Content.Client._Misfits.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class WhitelistSearchWindow : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _proto = default!;

    public Action<string>? OnSearch;
    public Action<NetUserId>? OnSelectPlayer;
    public Action<ProtoId<JobPrototype>, bool>? OnSetJob;

    private CancellationTokenSource? _searchDebounce;

    // #Misfits Change - Only show Fallout-relevant factions/departments in the whitelist GUI
    private static readonly HashSet<string> AllowedDepartments = new()
    {
        "BrotherhoodOfSteel",
        "CaesarLegion",
        "NCR",
        "Townsfolk",
        "FEVMutants",
        "Tribe",
        "Robots",
        "Vault",
        "Raider",
    };

    public WhitelistSearchWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SearchBox.OnTextChanged += OnSearchTextChanged;
        SearchBox.OnTextEntered += OnSearchTextEntered;
        SearchButton.OnPressed += OnSearchButtonPressed;
    }

    private void OnSearchButtonPressed(BaseButton.ButtonEventArgs args)
    {
        var query = SearchBox.Text.Trim();
        if (query.Length >= 2)
            OnSearch?.Invoke(query);
    }

    private void OnSearchTextEntered(LineEdit.LineEditEventArgs args)
    {
        _searchDebounce?.Cancel();
        var query = args.Text.Trim();
        if (query.Length >= 2)
            OnSearch?.Invoke(query);
    }

    private void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
    {
        _searchDebounce?.Cancel();
        _searchDebounce = new CancellationTokenSource();

        var query = args.Text.Trim();
        if (query.Length < 2)
        {
            SearchResults.RemoveAllChildren();
            return;
        }

        // Debounce 300ms so we don't spam the server on every keystroke
        Timer.Spawn(300, () =>
        {
            OnSearch?.Invoke(query);
        }, _searchDebounce.Token);
    }

    public void HandleState(WhitelistSearchEuiState state)
    {
        // Update search results
        SearchResults.RemoveAllChildren();
        foreach (var playerInfo in state.SearchResults)
        {
            var button = new Button
            {
                Text = playerInfo.UserName,
                HorizontalExpand = true,
            };
            var capturedId = playerInfo.UserId;
            button.OnPressed += _ => OnSelectPlayer?.Invoke(capturedId);
            SearchResults.AddChild(button);
        }

        // Update selected player info
        if (state.SelectedPlayerName != null && state.Whitelists != null)
        {
            SelectedPlayerLabel.Text = $"Whitelists for: {state.SelectedPlayerName}";
            UpdateDepartments(state.Whitelists);
        }
        else
        {
            SelectedPlayerLabel.Text = "No player selected";
            Departments.RemoveAllChildren();
        }
    }

    private void UpdateDepartments(HashSet<ProtoId<JobPrototype>> whitelists)
    {
        Departments.RemoveAllChildren();
        foreach (var proto in _proto.EnumeratePrototypes<DepartmentPrototype>())
        {
            if (!AllowedDepartments.Contains(proto.ID))
                continue;

            var panel = new DepartmentWhitelistPanel(proto, _proto, whitelists);
            panel.OnSetJob += (id, whitelisting) => OnSetJob?.Invoke(id, whitelisting);
            Departments.AddChild(panel);
        }
    }
}
