// #Misfits Change - Staff Panel tab with per-round ticket stats + action buttons
using System.Linq;
using Content.Client._Misfits.Administration.Systems;
using Content.Client._Misfits.Administration.UI;
using Content.Client.Administration.Systems;
using Content.Shared._Misfits.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Localization;
using Robust.Shared.Maths;

namespace Content.Client._Misfits.Administration.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class StaffTab : Control
{
    private TicketLogWindow? _ticketLogWindow;

    // Ticket data from both systems, keyed by (Type, TicketId)
    private readonly Dictionary<(HelpTicketType, int), HelpTicketInfo> _tickets = new();

    private BwoinkSystem? _bwoinkSys;
    private MentorHelpSystem? _mentorSys;

    public StaffTab()
    {
        RobustXamlLoader.Load(this);

        // Style the stats panel background
        StatsPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = new Color(30, 30, 50, 200),
            ContentMarginLeftOverride = 6,
            ContentMarginRightOverride = 6,
            ContentMarginTopOverride = 4,
            ContentMarginBottomOverride = 4,
        };

        // Subscribe to ticket events from both admin-help and mentor-help systems
        var entitySysMan = IoCManager.Resolve<IEntitySystemManager>();

        _bwoinkSys = entitySysMan.GetEntitySystem<BwoinkSystem>();
        _bwoinkSys.OnTicketUpdated += OnAdminTicketUpdated;
        _bwoinkSys.OnTicketListReceived += OnAdminTicketList;
        _bwoinkSys.RequestTicketList();

        _mentorSys = entitySysMan.GetEntitySystem<MentorHelpSystem>();
        _mentorSys.OnTicketUpdated += OnMentorTicketUpdated;
        _mentorSys.OnTicketListReceived += OnMentorTicketList;
        _mentorSys.RequestTicketList();

        // Ticket log button
        OpenTicketLog.OnPressed += _ =>
        {
            if (_ticketLogWindow is { Disposed: false })
            {
                _ticketLogWindow.MoveToFront();
                return;
            }

            _ticketLogWindow = new TicketLogWindow();
            _ticketLogWindow.OnClose += () => _ticketLogWindow = null; // Clear reference on close
            _ticketLogWindow.OpenCentered();
        };

        // Initial render with empty data
        RefreshStats();
    }

    private void OnAdminTicketUpdated(HelpTicketInfo ticket)
    {
        _tickets[(HelpTicketType.AdminHelp, ticket.TicketId)] = ticket;
        RefreshStats();
    }

    private void OnAdminTicketList(List<HelpTicketInfo> tickets)
    {
        foreach (var t in tickets)
            _tickets[(HelpTicketType.AdminHelp, t.TicketId)] = t;
        RefreshStats();
    }

    private void OnMentorTicketUpdated(HelpTicketInfo ticket)
    {
        _tickets[(HelpTicketType.MentorHelp, ticket.TicketId)] = ticket;
        RefreshStats();
    }

    private void OnMentorTicketList(List<HelpTicketInfo> tickets)
    {
        foreach (var t in tickets)
            _tickets[(HelpTicketType.MentorHelp, t.TicketId)] = t;
        RefreshStats();
    }

    /// <summary>
    /// Recomputes all stats from the in-memory ticket dictionary and updates labels + grid.
    /// </summary>
    private void RefreshStats()
    {
        var all = _tickets.Values.ToList();
        var total = all.Count;
        var open = all.Count(t => t.Status == HelpTicketStatus.Open);
        var claimed = all.Count(t => t.Status == HelpTicketStatus.Claimed);
        var resolved = all.Count(t => t.Status == HelpTicketStatus.Resolved);

        // Average resolution time (only for resolved tickets with timestamps)
        var resolvedWithTime = all
            .Where(t => t.Status == HelpTicketStatus.Resolved && t.ResolvedAt.HasValue)
            .ToList();

        string avgTimeStr;
        if (resolvedWithTime.Count > 0)
        {
            var avgSeconds = resolvedWithTime
                .Average(t => (t.ResolvedAt!.Value - t.CreatedAt).TotalSeconds);
            var avgSpan = TimeSpan.FromSeconds(avgSeconds);
            avgTimeStr = avgSpan.TotalMinutes >= 1
                ? $"{avgSpan.Minutes}m {avgSpan.Seconds}s"
                : $"{avgSpan.Seconds}s";
        }
        else
        {
            avgTimeStr = Loc.GetString("misfits-staff-stats-na");
        }

        // Update summary labels
        TotalTicketsLabel.Text = Loc.GetString("misfits-staff-stats-total", ("count", total));
        OpenTicketsLabel.Text = Loc.GetString("misfits-staff-stats-open", ("count", open));
        ClaimedTicketsLabel.Text = Loc.GetString("misfits-staff-stats-claimed", ("count", claimed));
        ResolvedTicketsLabel.Text = Loc.GetString("misfits-staff-stats-resolved", ("count", resolved));
        AvgResolutionLabel.Text = Loc.GetString("misfits-staff-stats-avg-time", ("time", avgTimeStr));

        // Color the open count red when there are unclaimed tickets
        OpenTicketsLabel.FontColorOverride = open > 0 ? Color.Red : null;

        // Build per-staff breakdown
        // Collect all staff who claimed or resolved at least one ticket
        var staffEntries = new Dictionary<string, (int claimedCount, int resolvedCount)>();

        foreach (var ticket in all)
        {
            if (ticket.ClaimedByName != null)
            {
                if (!staffEntries.TryGetValue(ticket.ClaimedByName, out var entry))
                    entry = (0, 0);
                entry.claimedCount++;
                staffEntries[ticket.ClaimedByName] = entry;
            }

            if (ticket.ResolvedByName != null && ticket.ResolvedByName != "System")
            {
                if (!staffEntries.TryGetValue(ticket.ResolvedByName, out var entry))
                    entry = (0, 0);
                entry.resolvedCount++;
                staffEntries[ticket.ResolvedByName] = entry;
            }
        }

        // Rebuild the grid
        StaffGrid.RemoveAllChildren();

        if (staffEntries.Count == 0)
        {
            // No staff activity yet — show a hint
            var noData = new Label
            {
                Text = Loc.GetString("misfits-staff-stats-no-activity"),
                StyleClasses = { "LabelSubText" },
            };
            StaffGrid.AddChild(noData);
            return;
        }

        // Header row
        AddGridHeader(Loc.GetString("misfits-staff-stats-col-name"));
        AddGridHeader(Loc.GetString("misfits-staff-stats-col-claimed"));
        AddGridHeader(Loc.GetString("misfits-staff-stats-col-resolved"));
        AddGridHeader(Loc.GetString("misfits-staff-stats-col-ratio"));

        // Data rows sorted by total activity descending
        foreach (var (name, (claimedC, resolvedC)) in staffEntries.OrderByDescending(e => e.Value.claimedCount + e.Value.resolvedCount))
        {
            var ratio = total > 0
                ? $"{(double)(claimedC + resolvedC) / total * 100:F0}%"
                : "0%";

            AddGridCell(name);
            AddGridCell(claimedC.ToString());
            AddGridCell(resolvedC.ToString());
            AddGridCell(ratio);
        }
    }

    private void AddGridHeader(string text)
    {
        StaffGrid.AddChild(new Label
        {
            Text = text,
            StyleClasses = { "LabelSubText" },
            FontColorOverride = Color.LightGray,
        });
    }

    private void AddGridCell(string text)
    {
        StaffGrid.AddChild(new Label
        {
            Text = text,
            StyleClasses = { "LabelSubText" },
        });
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (_bwoinkSys != null)
        {
            _bwoinkSys.OnTicketUpdated -= OnAdminTicketUpdated;
            _bwoinkSys.OnTicketListReceived -= OnAdminTicketList;
        }

        if (_mentorSys != null)
        {
            _mentorSys.OnTicketUpdated -= OnMentorTicketUpdated;
            _mentorSys.OnTicketListReceived -= OnMentorTicketList;
        }
    }
}
