// #Misfits Change - Staff Panel tab for admin menu (permissions + ticket log button)
using Content.Client._Misfits.Administration.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.Administration.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class StaffTab : Control
{
    private TicketLogWindow? _ticketLogWindow;

    public StaffTab()
    {
        RobustXamlLoader.Load(this);

        // #Misfits Add — open/toggle the ticket log window
        OpenTicketLog.OnPressed += _ =>
        {
            if (_ticketLogWindow is { Disposed: false })
            {
                _ticketLogWindow.MoveToFront();
                return;
            }

            _ticketLogWindow = new TicketLogWindow();
            _ticketLogWindow.OpenCentered();
        };
    }
}
