// #Misfits Change - Whitelisting tab for admin menu
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.Administration.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class WhitelistingTab : Control
{
    public WhitelistingTab()
    {
        RobustXamlLoader.Load(this);
    }
}
