using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class AdminMenuWindow : DefaultWindow
{
    public event Action? OnDisposed;

    public AdminMenuWindow()
    {
        MinSize = new Vector2(850, 250); // Corvax-Change old 650, 250
        Title = Loc.GetString("admin-menu-title");
        RobustXamlLoader.Load(this);
        // #Misfits Change - Reordered: Players first
        MasterTabContainer.SetTabTitle((int) TabIndex.Players, Loc.GetString("admin-menu-players-tab"));
        MasterTabContainer.SetTabTitle((int) TabIndex.Admin, Loc.GetString("admin-menu-admin-tab"));
        MasterTabContainer.SetTabTitle((int) TabIndex.Adminbus, Loc.GetString("admin-menu-adminbus-tab"));
        MasterTabContainer.SetTabTitle((int) TabIndex.Atmos, Loc.GetString("admin-menu-atmos-tab"));
        MasterTabContainer.SetTabTitle((int) TabIndex.Round, Loc.GetString("admin-menu-round-tab"));
        MasterTabContainer.SetTabTitle((int) TabIndex.Server, Loc.GetString("admin-menu-server-tab"));
        MasterTabContainer.SetTabTitle((int) TabIndex.PanicBunker, Loc.GetString("admin-menu-panic-bunker-tab"));
        MasterTabContainer.SetTabTitle((int) TabIndex.Objects, Loc.GetString("admin-menu-objects-tab"));
        // #Misfits Change - Whitelisting tab
        MasterTabContainer.SetTabTitle((int) TabIndex.Whitelisting, Loc.GetString("misfits-admin-menu-whitelisting-tab"));
        // #Misfits Change - Staff tab
        MasterTabContainer.SetTabTitle((int) TabIndex.Staff, Loc.GetString("misfits-admin-menu-staff-tab"));
        // #Misfits Change - LoreMaster tab (faction objective management)
        MasterTabContainer.SetTabTitle((int) TabIndex.LoreMaster, Loc.GetString("misfits-admin-menu-loremaster-tab"));
        MasterTabContainer.OnTabChanged += OnTabChanged;
    }

    private void OnTabChanged(int tabIndex)
    {
        var tabEnum = (TabIndex)tabIndex;
        if (tabEnum == TabIndex.Objects)
            ObjectsTabControl.RefreshObjectList();
    }

    protected override void Dispose(bool disposing)
    {
        OnDisposed?.Invoke();
        base.Dispose(disposing);
        OnDisposed = null;
    }

    // #Misfits Change - Reordered: Players first
    private enum TabIndex
    {
        Players = 0,
        Admin,
        Adminbus,
        Atmos,
        Round,
        Server,
        PanicBunker,
        Objects,
        Whitelisting, // #Misfits Change
        Staff, // #Misfits Change
        LoreMaster, // #Misfits Change
    }
}
