# Renamed to: sergeant.yml, staff_sergeant.yml, first_sergeant.yml
# - type: job
#   id: NCRSGT
#   setPreference: true
#   weight: 50
#   overrideConsoleVisibility: false
#   canBeAntag: false
#   name: job-name-ncr-sergeant
#   description: job-description-ncr-sergeant
#   playTimeTracker: NCRNCO
#   requirements:
#     - !type:CharacterSpeciesRequirement
#       species:
#       - Human
#       - Ghoul
#     - !type:CharacterDepartmentTimeRequirement
#       department: NCR
#       min: 0 # 20 hours Corvax-Change
#     - !type:CharacterPlaytimeRequirement # Corvax-Add
#       tracker: NCRSoldier
#       min: 0 # 10 hours
#   startingGear: NCRSGTGear
#   icon: "JobIconNcrSerg" # Corvax-Change
#   supervisors: job-supervisors-ncr-staff-sergeant
#   alwaysUseSpawner: true
#   access:
#   - NCR
#   - NCRSGT
#   special:
#   - !type:AddComponentSpecial
#     components:
#       - type: NpcFactionMember
#         factions:
#           - Wastelander
#           - NCR
# 
# - type: startingGear
#   id: NCRSGTGear
#   equipment:
#     back: N14ClothingBackpackNCR # Corvax-Change
#     gloves: N14ClothingHandsGlovesCombat
#     jumpsuit: N14ClothingOfficerUniformNCRDesert # Corvax-Change
#     shoes: N14ClothingBootsCombatFilled
#     neck: N14ClothingNeckMantleNCR
#     belt: ClothingBeltNCR
#     outerClothing: N14ClothingOuterNCRCombatArmor
#     pocket1: NCRSGTloadoutkits
#     pocket2: RadioHandheld
#     id: N14IDNCRDogtagNCO
#   innerClothingSkirt: N14ClothingOfficerUniformNCRDesert # Corvax-Change
#   satchel: N14ClothingBackpackSatchelNCRFilled
#   storage: # Corvax-Change
#     back:
#     - N14BoxPlasticFilledMilitaryNCR
# 
# - type: playTimeTracker
#   id: NCRNCO
# 
# - type: playTimeTracker
#   id: NCRStaffSergeant
# 
# - type: playTimeTracker
#   id: NCRFirstSergeant
# 
# - type: job
#   id: NCRStaffSergeant
#   setPreference: true
#   weight: 60
#   overrideConsoleVisibility: false
#   canBeAntag: false
#   name: job-name-ncr-staff-sergeant
#   description: job-description-ncr-staff-sergeant
#   playTimeTracker: NCRStaffSergeant
#   requirements:
#     - !type:CharacterSpeciesRequirement
#       species:
#       - Human
#       - Ghoul
#     - !type:CharacterDepartmentTimeRequirement
#       department: NCR
#       min: 0
#     - !type:CharacterPlaytimeRequirement
#       tracker: NCRNCO
#       min: 0
#   startingGear: NCRSGTGear
#   icon: "JobIconNcrSerg"
#   supervisors: job-supervisors-ncr-first-sergeant
#   alwaysUseSpawner: true
#   access:
#   - NCR
#   - NCRSGT
#   special:
#   - !type:AddComponentSpecial
#     components:
#       - type: NpcFactionMember
#         factions:
#           - Wastelander
#           - NCR
# 
# - type: job
#   id: NCRFirstSergeant
#   setPreference: true
#   weight: 70
#   overrideConsoleVisibility: false
#   canBeAntag: false
#   name: job-name-ncr-first-sergeant
#   description: job-description-ncr-first-sergeant
#   playTimeTracker: NCRFirstSergeant
#   requirements:
#     - !type:CharacterSpeciesRequirement
#       species:
#       - Human
#       - Ghoul
#     - !type:CharacterDepartmentTimeRequirement
#       department: NCR
#       min: 0
#     - !type:CharacterPlaytimeRequirement
#       tracker: NCRStaffSergeant
#       min: 0
#   startingGear: NCRSGTGear
#   icon: "JobIconNcrSerg"
#   supervisors: job-supervisors-ncr-lt
#   alwaysUseSpawner: true
#   access:
#   - NCR
#   - NCRSGT
#   special:
#   - !type:AddComponentSpecial
#     components:
#       - type: NpcFactionMember
#         factions:
#           - Wastelander
#           - NCR
