// #Misfits Change - Currency wallet dedicated HUD button widget
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Utility;

namespace Content.Client._Misfits.Currency.Widgets;

[GenerateTypedNameReferences]
public sealed partial class CurrencyWalletGui : UIWidget
{
    public event Action? OnWalletPressed;

    public CurrencyWalletGui()
    {
        RobustXamlLoader.Load(this);

        // Use IResourceCache directly — safe at startup before entity systems are ready
        var resCache = IoCManager.Resolve<IResourceCache>();
        var texPath = new ResPath("/Textures/_Nuclear14/Objects/Misc/currency.rsi/caps3.png");
        if (resCache.TryGetResource<TextureResource>(texPath, out var tex))
            WalletButton.TextureNormal = tex.Texture;

        WalletButton.OnPressed += _ => OnWalletPressed?.Invoke();
    }
}
