- type: job
  id: CaesarLegionRecruit
  setPreference: true
  weight: 20
  showBorder: true
  name: job-name-caesar-legion-recruit
  description: job-description-caesar-legion-recruit
  playTimeTracker: CaesarLegionRecruit
  requirements:
  - !type:CharacterSpeciesRequirement
    species:
    - Human
  - !type:CharacterSexRequirement
    sex: Male
  - !type:CharacterGenderRequirement
    gender: Male
  - !type:CharacterOverallTimeRequirement
    min: 0
  startingGear: CaesarLegionRecruitGear
  alwaysUseSpawner: true
  icon: "JobIconlegionerRecruit"
  supervisors: job-name-caesar-legion-other
  canBeAntag: false
  access:
  - CaesarLegionRecruit
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - CaesarLegion
      - type: ReplacementAccent
        accent: latin
  - !type:AddTraitSpecial
    traits: [ LanguageLatin ]

- type: startingGear
  id: CaesarLegionRecruitGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitRags
    mask: N14ClothingMaskBrownMask
    back: N14ClothingBackpackMilitary
    shoes: N14ClothingBootsLeather
    head: N14ClothingHeadHatTribalOutcastHood
    gloves: N14ClothingHandsGlovesTribal
    id: N14IDLegionaryBadgeRecruit

- type: playTimeTracker
  id: CaesarLegionRecruit
