# Renamed to: legate.yml, veteran_decanus.yml, vexillarius.yml, houndmaster.yml, legion_recruit.yml
# - type: job
#   id: CaesarLegionLegate
#   setPreference: true
#   weight: 120
#   name: job-name-caesar-legion-legate
#   description: job-description-caesar-legion-legate
#   playTimeTracker: CaesarLegionLegate
#   requirements:
#   - !type:CharacterDepartmentTimeRequirement
#       department: CaesarLegion
#       min: 288000 # 80 hours
#   - !type:CharacterPlaytimeRequirement
#       tracker: CaesarLegionCenturion
#       min: 43200 # 12 hours
#   - !type:CharacterSpeciesRequirement
#     species:
#     - Human
#   - !type:CharacterSexRequirement
#     sex: Male
#   - !type:CharacterGenderRequirement
#     gender: Male
#   startingGear: CaesarLegionLegateGear
#   alwaysUseSpawner: true
#   icon: "JobIconlegionerCenturion"
#   supervisors: job-name-caesar-legion
#   canBeAntag: false
#   requireAdminNotify: true
#   access:
#   - CaesarLegionLegate
#   special:
#   - !type:AddComponentSpecial
#     components:
#       - type: NpcFactionMember
#         factions:
#           - CaesarLegion
#       - type: ReplacementAccent
#         accent: latin
#   - !type:AddTraitSpecial
#     traits: [ LanguageLatin ]
# 
# - type: startingGear
#   id: CaesarLegionLegateGear
#   equipment:
#     jumpsuit: N14ClothingUniformJumpsuitLegionnaire
#     neck: ClothingNeckRedScarf
#     eyes: N14ClothingEyesGlassesWelding
#     back: N14ClothingBackpackMilitary
#     shoes: N14ClothingBootsLegate
#     head: N14ClothingHeadHatLegateHelmet
#     gloves: N14ClothingHandsGlovesLegate
#     outerClothing: N14ClothingOuterLegateArmor
#     belt: N14Gladius
#     pocket1: LegionCenturionloadoutkits
#     pocket2: N14WeaponPistol10mmPipe
#     id: N14IDLegionaryMedalLegate
#   innerClothingSkirt: N14ClothingUniformJumpsuitLegionnaireOther
#   storage:
#     back:
#     - N14BoxPlasticFilledMilitary
# 
# - type: playTimeTracker
#   id: CaesarLegionLegate
# 
# - type: job
#   id: CaesarLegionVeteranDecanus
#   setPreference: true
#   weight: 100
#   name: job-name-caesar-legion-veteran-decanus
#   description: job-description-caesar-legion-veteran-decanus
#   playTimeTracker: CaesarLegionVeteranDecanus
#   requirements:
#   - !type:CharacterDepartmentTimeRequirement
#       department: CaesarLegion
#       min: 108000 # 30 hours
#   - !type:CharacterPlaytimeRequirement
#       tracker: CaesarLegionDean
#       min: 18000 # 5 hours
#   - !type:CharacterSpeciesRequirement
#     species:
#     - Human
#   - !type:CharacterSexRequirement
#     sex: Male
#   - !type:CharacterGenderRequirement
#     gender: Male
#   startingGear: CaesarLegionVeteranDecanusGear
#   alwaysUseSpawner: true
#   icon: "JobIconlegionerDean"
#   supervisors: job-name-caesar-legion-supervisors
#   canBeAntag: false
#   access:
#   - CaesarLegionVeteranDecanus
#   special:
#   - !type:AddComponentSpecial
#     components:
#       - type: NpcFactionMember
#         factions:
#           - CaesarLegion
#       - type: ReplacementAccent
#         accent: latin
#   - !type:AddTraitSpecial
#     traits: [ LanguageLatin ]
# 
# - type: startingGear
#   id: CaesarLegionVeteranDecanusGear
#   equipment:
#     jumpsuit: N14ClothingUniformJumpsuitLegionnaire
#     neck: ClothingNeckRedScarf
#     eyes: N14ClothingEyesGlassesWelding
#     back: N14ClothingBackpackMilitary
#     shoes: N14ClothingBootsBlack
#     head: N14ClothingHeadHatDeanVeteranHelmet
#     gloves: N14ClothingHandsGlovesTribal
#     outerClothing: N14ClothingOuterDeanLegionnaireVeteranArmor
#     belt: N14Gladius
#     pocket1: LegionDeanloadoutkits
#     pocket2: N14WeaponPistol10mmPipe
#     id: N14IDLegionaryMedalVeteranDecanus
#   innerClothingSkirt: N14ClothingUniformJumpsuitLegionnaireOther
#   storage:
#     back:
#     - N14BoxPlasticFilledMilitary
# 
# - type: playTimeTracker
#   id: CaesarLegionVeteranDecanus
# 
# - type: job
#   id: CaesarLegionVexillarius
#   setPreference: true
#   weight: 40
#   name: job-name-caesar-legion-vexillarius
#   description: job-description-caesar-legion-vexillarius
#   playTimeTracker: CaesarLegionVexillarius
#   requirements:
#   - !type:CharacterDepartmentTimeRequirement
#       department: CaesarLegion
#       min: 0
#   - !type:CharacterSpeciesRequirement
#     species:
#     - Human
#   - !type:CharacterSexRequirement
#     sex: Male
#   - !type:CharacterGenderRequirement
#     gender: Male
#   startingGear: CaesarLegionVexillariusGear
#   alwaysUseSpawner: true
#   icon: "JobIconlegionerVenator"
#   supervisors: job-name-caesar-legion-other
#   canBeAntag: false
#   access:
#   - CaesarLegionVexillarius
#   special:
#   - !type:AddComponentSpecial
#     components:
#       - type: NpcFactionMember
#         factions:
#           - CaesarLegion
#       - type: ReplacementAccent
#         accent: latin
#   - !type:AddTraitSpecial
#     traits: [ LanguageLatin ]
# 
# - type: startingGear
#   id: CaesarLegionVexillariusGear
#   equipment:
#     jumpsuit: N14ClothingUniformJumpsuitLegionnaire
#     neck: N14ClothingNeckCloakLegionWhite
#     mask: N14ClothingMaskBrownMask
#     back: N14ClothingBackpackMilitary
#     shoes: N14ClothingShoesKaligi
#     head: N14ClothingHeadHatVenator
#     gloves: N14ClothingHandsGlovesTribal
#     belt: N14Gladius
#     suitstorage: N14PilumSpear
#     pocket1: LegionRecruitloadoutkits
#     id: N14IDLegionaryMedalVexillarius
#   innerClothingSkirt: N14ClothingUniformJumpsuitLegionnaireOther
#   storage:
#     back:
#     - N14BoxPlasticFilledMilitary
# 
# - type: playTimeTracker
#   id: CaesarLegionVexillarius
# 
# - type: job
#   id: CaesarLegionHoundmaster
#   setPreference: true
#   weight: 30
#   name: job-name-caesar-legion-houndmaster
#   description: job-description-caesar-legion-houndmaster
#   playTimeTracker: CaesarLegionHoundmaster
#   requirements:
#   - !type:CharacterDepartmentTimeRequirement
#       department: CaesarLegion
#       min: 0
#   - !type:CharacterSpeciesRequirement
#     species:
#     - Human
#   - !type:CharacterSexRequirement
#     sex: Male
#   - !type:CharacterGenderRequirement
#     gender: Male
#   startingGear: CaesarLegionHoundmasterGear
#   alwaysUseSpawner: true
#   icon: "JobIconlegionerWarrior"
#   supervisors: job-name-caesar-legion-other
#   canBeAntag: false
#   access:
#   - CaesarLegionHoundmaster
#   special:
#   - !type:AddComponentSpecial
#     components:
#       - type: NpcFactionMember
#         factions:
#           - CaesarLegion
#       - type: ReplacementAccent
#         accent: latin
#   - !type:AddTraitSpecial
#     traits: [ LanguageLatin, N14PetDogLegion ]
# 
# - type: startingGear
#   id: CaesarLegionHoundmasterGear
#   equipment:
#     jumpsuit: N14ClothingUniformJumpsuitLegionnaire
#     mask: N14ClothingMaskBrownMask
#     back: N14ClothingBackpackMilitary
#     shoes: N14ClothingShoesKaligi
#     head: N14ClothingHeadHatTribalOutcastHood
#     gloves: N14ClothingHandsGlovesTribal
#     belt: N14Gladius
#     pocket1: LegionRecruitloadoutkits
#     id: N14IDLegionaryMedalHoundmaster
#   innerClothingSkirt: N14ClothingUniformJumpsuitLegionnaireOther
#   storage:
#     back:
#     - N14BoxPlasticFilledMilitary
# 
# - type: playTimeTracker
#   id: CaesarLegionHoundmaster
# 
# - type: job
#   id: CaesarLegionRecruit
#   setPreference: true
#   weight: 20
#   name: job-name-caesar-legion-recruit
#   description: job-description-caesar-legion-recruit
#   playTimeTracker: CaesarLegionRecruit
#   requirements:
#   - !type:CharacterSpeciesRequirement
#     species:
#     - Human
#   - !type:CharacterSexRequirement
#     sex: Male
#   - !type:CharacterGenderRequirement
#     gender: Male
#   - !type:CharacterOverallTimeRequirement
#     min: 0
#   startingGear: CaesarLegionRecruitGear
#   alwaysUseSpawner: true
#   icon: "JobIconlegionerRecruit"
#   supervisors: job-name-caesar-legion-other
#   canBeAntag: false
#   access:
#   - CaesarLegionRecruit
#   special:
#   - !type:AddComponentSpecial
#     components:
#       - type: NpcFactionMember
#         factions:
#           - CaesarLegion
#       - type: ReplacementAccent
#         accent: latin
#   - !type:AddTraitSpecial
#     traits: [ LanguageLatin ]
# 
# - type: startingGear
#   id: CaesarLegionRecruitGear
#   equipment:
#     jumpsuit: N14ClothingUniformJumpsuitRags
#     mask: N14ClothingMaskBrownMask
#     back: N14ClothingBackpackMilitary
#     shoes: N14ClothingShoesTribal
#     head: N14ClothingHeadHatTribalOutcastHood
#     gloves: N14ClothingHandsGlovesTribal
#     id: N14IDLegionaryBadgeRecruit
# 
# - type: playTimeTracker
#   id: CaesarLegionRecruit