// #Misfits Change - Wasteland Map Viewer Window
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using Content.Client.UserInterface.Controls;

namespace Content.Client._Misfits.WastelandMap;

[GenerateTypedNameReferences]
public sealed partial class WastelandMapWindow : FancyWindow
{
    public WastelandMapWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void SetMap(string title, ResPath texturePath)
    {
        MapTitle.Text = title;
        Title = title;

        var resourceCache = IoCManager.Resolve<IResourceCache>();
        var fullPath = new ResPath("/Textures") / texturePath;

        if (resourceCache.TryGetResource<TextureResource>(fullPath, out var textureResource))
        {
            MapTexture.Texture = textureResource;
        }
    }
}
