using System.Linq;
using Content.Client.Station;
using Content.Shared.Armor;
using Content.Shared.Item;
using Content.Shared.Mobs.Components;
using Content.Shared.Weapons.Melee;
using Content.Shared.Weapons.Ranged.Components;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Map.Components;
using Robust.Shared.Player; // #Misfits Change - needed for ActorComponent (player-controlled entity check)

namespace Content.Client.Administration.UI.Tabs.ObjectsTab;

[GenerateTypedNameReferences]
public sealed partial class ObjectsTab : Control
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private readonly Color _altColor = Color.FromHex("#292B38");
    private readonly Color _defaultColor = Color.FromHex("#2F2F3B");

    private bool _ascending;
    private ObjectsTabHeader.Header _headerClicked = ObjectsTabHeader.Header.ObjectName;

    private readonly List<ObjectsTabSelection> _selections = [];
    public event Action<GUIBoundKeyEventArgs, ListData>? OnEntryKeyBindDown;

    public ObjectsTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ObjectTypeOptions.OnItemSelected += ev =>
        {
            ObjectTypeOptions.SelectId(ev.Id);
            RefreshObjectList(_selections[ev.Id]);
        };

        foreach (var type in Enum.GetValues<ObjectsTabSelection>())
        {
            _selections.Add(type);
            ObjectTypeOptions.AddItem(GetLocalizedEnumValue(type));
        }

        ListHeader.OnHeaderClicked += HeaderClicked;
        SearchList.SearchBar = SearchLineEdit;
        SearchList.GenerateItem += GenerateButton;
        SearchList.DataFilterCondition += DataFilterCondition;
        SearchList.ItemKeyBindDown += (args, data) => OnEntryKeyBindDown?.Invoke(args, data);
        RefreshListButton.OnPressed += _ => RefreshObjectList();

        var defaultSelection = ObjectsTabSelection.Grids;
        ObjectTypeOptions.SelectId((int) defaultSelection);
        RefreshObjectList(defaultSelection);
    }

    public void RefreshObjectList()
    {
        RefreshObjectList(_selections[ObjectTypeOptions.SelectedId]);
    }

    private void RefreshObjectList(ObjectsTabSelection selection)
    {
        var entities = new List<(string Name, NetEntity Entity)>();
        switch (selection)
        {
            case ObjectsTabSelection.Entities:
                AddGenericEntities(entities);
                break;
            case ObjectsTabSelection.Mobs:
                AddMobs(entities);
                break;
            case ObjectsTabSelection.Stations:
                entities.AddRange(_entityManager.EntitySysManager.GetEntitySystem<StationSystem>().Stations);
                break;
            case ObjectsTabSelection.Grids:
            {
                var query = _entityManager.AllEntityQueryEnumerator<MapGridComponent, MetaDataComponent>();
                while (query.MoveNext(out var uid, out _, out var metadata))
                {
                    entities.Add((metadata.EntityName, _entityManager.GetNetEntity(uid)));
                }

                break;
            }
            case ObjectsTabSelection.Maps:
            {
                var query = _entityManager.AllEntityQueryEnumerator<MapComponent, MetaDataComponent>();
                while (query.MoveNext(out var uid, out _, out var metadata))
                {
                    entities.Add((metadata.EntityName, _entityManager.GetNetEntity(uid)));
                }

                break;
            }
            case ObjectsTabSelection.Weapons:
                AddWeapons(entities);
                break;
            case ObjectsTabSelection.Armor:
                AddArmor(entities);
                break;
            default:
                throw new ArgumentOutOfRangeException(nameof(selection), selection, null);
        }

        entities.Sort((a, b) =>
        {
            var valueA = GetComparableValue(a, _headerClicked);
            var valueB = GetComparableValue(b, _headerClicked);
            return _ascending
                ? Comparer<object>.Default.Compare(valueA, valueB)
                : Comparer<object>.Default.Compare(valueB, valueA);
        });

        var listData = new List<ObjectsListData>();
        for (var index = 0; index < entities.Count; index++)
        {
            var info = entities[index];
            listData.Add(new ObjectsListData(info,
                $"{info.Name} {info.Entity}",
                index % 2 == 0 ? _altColor : _defaultColor));
        }

        SearchList.PopulateList(listData);
    }

    private void AddGenericEntities(List<(string Name, NetEntity Entity)> entities)
    {
        var stations = _entityManager.EntitySysManager.GetEntitySystem<StationSystem>().Stations;
        var query = _entityManager.AllEntityQueryEnumerator<TransformComponent, MetaDataComponent>();
        while (query.MoveNext(out var uid, out _, out var metadata))
        {
            if (!IsGenericEntity(uid, stations))
                continue;

            entities.Add((metadata.EntityName, _entityManager.GetNetEntity(uid)));
        }
    }

    private void AddMobs(List<(string Name, NetEntity Entity)> entities)
    {
        // #Misfits Change - Exclude player-controlled entities (ActorComponent = has a player session attached)
        // so that "Mobs" only shows NPCs, not connected players.
        var query = _entityManager.AllEntityQueryEnumerator<MobStateComponent, MetaDataComponent>();
        while (query.MoveNext(out var uid, out _, out var metadata))
        {
            if (_entityManager.HasComponent<ActorComponent>(uid))
                continue;

            entities.Add((metadata.EntityName, _entityManager.GetNetEntity(uid)));
        }
    }

    private void AddWeapons(List<(string Name, NetEntity Entity)> entities)
    {
        var query = _entityManager.AllEntityQueryEnumerator<ItemComponent, MetaDataComponent>();
        while (query.MoveNext(out var uid, out _, out var metadata))
        {
            if (!IsWeapon(uid))
                continue;

            entities.Add((metadata.EntityName, _entityManager.GetNetEntity(uid)));
        }
    }

    private void AddArmor(List<(string Name, NetEntity Entity)> entities)
    {
        var query = _entityManager.AllEntityQueryEnumerator<ItemComponent, MetaDataComponent>();
        while (query.MoveNext(out var uid, out _, out var metadata))
        {
            if (!_entityManager.HasComponent<ArmorComponent>(uid))
                continue;

            entities.Add((metadata.EntityName, _entityManager.GetNetEntity(uid)));
        }
    }

    private bool IsGenericEntity(EntityUid uid, IReadOnlyList<(string Name, NetEntity Entity)> stations)
    {
        var netEntity = _entityManager.GetNetEntity(uid);
        return !_entityManager.HasComponent<MapGridComponent>(uid)
               && !_entityManager.HasComponent<MapComponent>(uid)
               && !stations.Any(station => station.Entity == netEntity);
    }

    private bool IsWeapon(EntityUid uid)
    {
        return _entityManager.HasComponent<GunComponent>(uid)
               || _entityManager.HasComponent<MeleeWeaponComponent>(uid);
    }

    private void GenerateButton(ListData data, ListContainerButton button)
    {
        if (data is not ObjectsListData { Info: var info, BackgroundColor: var backgroundColor })
            return;

        var entry = new ObjectsTabEntry(info.Name,
            info.Entity,
            new StyleBoxFlat { BackgroundColor = backgroundColor });
        button.ToolTip = $"{info.Name}, {info.Entity}";

        button.AddChild(entry);
    }

    private bool DataFilterCondition(string filter, ListData listData)
    {
        if (listData is not ObjectsListData { FilteringString: var filteringString })
            return false;

        // If the filter is empty, do not filter out any entries
        if (string.IsNullOrEmpty(filter))
            return true;

        return filteringString.Contains(filter, StringComparison.CurrentCultureIgnoreCase);
    }

    private object GetComparableValue((string Name, NetEntity Entity) entity, ObjectsTabHeader.Header header)
    {
        return header switch
        {
            ObjectsTabHeader.Header.ObjectName => entity.Name,
            ObjectsTabHeader.Header.EntityID => entity.Entity.ToString(),
            _ => entity.Name,
        };
    }

    private void HeaderClicked(ObjectsTabHeader.Header header)
    {
        if (_headerClicked == header)
        {
            _ascending = !_ascending;
        }
        else
        {
            _headerClicked = header;
            _ascending = true;
        }

        ListHeader.UpdateHeaderSymbols(_headerClicked, _ascending);
        RefreshObjectList();
    }

    private string GetLocalizedEnumValue(ObjectsTabSelection selection)
    {
        return selection switch
        {
            ObjectsTabSelection.Entities => Loc.GetString("object-tab-object-type-entities"),
            ObjectsTabSelection.Grids => Loc.GetString("object-tab-object-type-grids"),
            ObjectsTabSelection.Maps => Loc.GetString("object-tab-object-type-maps"),
            ObjectsTabSelection.Mobs => Loc.GetString("object-tab-object-type-mobs"),
            ObjectsTabSelection.Stations => Loc.GetString("object-tab-object-type-stations"),
            ObjectsTabSelection.Weapons => Loc.GetString("object-tab-object-type-weapons"),
            ObjectsTabSelection.Armor => Loc.GetString("object-tab-object-type-armor"),
            _ => throw new ArgumentOutOfRangeException(nameof(selection), selection, null),
        };
    }

    private enum ObjectsTabSelection
    {
        Entities,
        Grids,
        Maps,
        Mobs,
        Stations,
        Weapons,
        Armor,
    }
}

public record ObjectsListData((string Name, NetEntity Entity) Info, string FilteringString, Color BackgroundColor)
    : ListData;
