name: No submodule update checker

on:
  pull_request:
    paths:
      - 'RobustToolbox'

jobs:
  this_aint_right:
    # #Misfits Add - Added Cythisiax to submodule update allowlist
    if: github.actor != 'sleepyyapril' && github.actor != 'VMSolidus' && github.actor != 'DEATHB4DEFEAT' && github.actor != 'Cythisiax'
    name: Submodule update in pr found
    runs-on: ubuntu-latest
    steps:
      - name: Fail
        run: exit 1
